package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, April 10, 2010 7:01:00 PM EAT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
